import React, { createContext, useContext, useMemo, useReducer } from 'react';

export const categories = ['All', 'Breakfast', 'Lunch', 'Dinner', 'Desserts', 'Snacks', 'Drinks'];
export const diets = ['All', 'Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free', 'Keto'];
export const timeOptions = ['Any', 'Under 15min', 'Under 30min', 'Under 1hr'];

export const recipes = [
 {
 id: 'r1',
 emoji: '',
 name: 'Smashed Avo Toast',
 category: 'Breakfast',
 diet: ['Vegetarian'],
 prepTime: '5min',
 cookTime: '5min',
 totalMinutes: 10,
 servings: '2 servings',
 difficulty: 'Easy',
 calories: '320cal',
 rating: 4.8,
 ratingCount: 1240,
 description: 'The café classic, perfected at home. Creamy avocado on sourdough with a perfectly poached egg.',
 ingredients: ['2 slices sourdough', '1 ripe avocado', '2 eggs', 'Lemon juice', 'Chilli flakes', 'Salt & pepper', 'Microgreens'],
 steps: ['Toast sourdough until golden', 'Mash avocado with lemon juice, salt and pepper', 'Poach eggs in simmering water for 3 minutes', 'Spread avo on toast', 'Top with poached egg, chilli flakes and microgreens'],
 },
 {
 id: 'r2',
 emoji: '',
 name: 'Cacio e Pepe',
 category: 'Dinner',
 diet: ['Vegetarian'],
 prepTime: '5min',
 cookTime: '15min',
 totalMinutes: 20,
 servings: '2 servings',
 difficulty: 'Medium',
 calories: '520cal',
 rating: 4.9,
 ratingCount: 892,
 description: 'Roman pasta perfection — just cheese, pepper and pasta water. The technique is everything.',
 ingredients: ['200g tonnarelli or spaghetti', '80g Pecorino Romano (finely grated)', '1 tbsp black pepper (coarsely ground)', '200ml pasta water', 'Salt'],
 steps: ['Boil pasta in lightly salted water', 'Toast pepper in a dry pan until fragrant', 'Reserve 200ml pasta water', 'Drain pasta and toss with pepper', 'Add pasta water gradually while adding cheese, tossing constantly to form a creamy sauce'],
 },
 {
 id: 'r3',
 emoji: '',
 name: 'Quinoa Power Bowl',
 category: 'Lunch',
 diet: ['Vegan', 'Gluten-Free'],
 prepTime: '10min',
 cookTime: '20min',
 totalMinutes: 30,
 servings: '2 servings',
 difficulty: 'Easy',
 calories: '410cal',
 rating: 4.7,
 ratingCount: 567,
 description: 'A vibrant bowl with fluffy quinoa, roasted veg, greens and a zingy tahini drizzle.',
 ingredients: ['1 cup quinoa', '1 sweet potato', '1 cup chickpeas', '2 handfuls baby spinach', '1 avocado', '2 tbsp tahini', 'Lemon juice', 'Olive oil'],
 steps: ['Cook quinoa until fluffy', 'Roast sweet potato and chickpeas for 20 minutes', 'Whisk tahini with lemon juice and water', 'Layer spinach, quinoa and roasted veg in bowls', 'Top with avocado and drizzle with dressing'],
 },
 {
 id: 'r4',
 emoji: '',
 name: 'Flourless Chocolate Cake',
 category: 'Desserts',
 diet: ['Gluten-Free', 'Vegetarian'],
 prepTime: '20min',
 cookTime: '35min',
 totalMinutes: 55,
 servings: '8 servings',
 difficulty: 'Medium',
 calories: '380cal',
 rating: 4.9,
 ratingCount: 2100,
 description: 'Intensely chocolatey with a delicate crackled top and fudgy centre.',
 ingredients: ['200g dark chocolate', '150g butter', '1 cup caster sugar', '4 eggs', '1/2 cup cocoa powder', 'Pinch of salt', 'Whipped cream to serve'],
 steps: ['Melt chocolate and butter together', 'Whisk eggs and sugar until glossy', 'Fold cocoa and salt into the chocolate mixture', 'Combine everything and pour into a lined tin', 'Bake for 35 minutes and cool before slicing'],
 },
 {
 id: 'r5',
 emoji: '',
 name: 'Thai Green Curry',
 category: 'Dinner',
 diet: ['Dairy-Free'],
 prepTime: '15min',
 cookTime: '25min',
 totalMinutes: 40,
 servings: '4 servings',
 difficulty: 'Medium',
 calories: '480cal',
 rating: 4.8,
 ratingCount: 1450,
 description: 'Creamy coconut curry loaded with crisp vegetables, herbs and bold green curry paste.',
 ingredients: ['2 tbsp green curry paste', '400ml coconut milk', '400g chicken or tofu', '1 zucchini', '1 red capsicum', '1 cup snow peas', 'Thai basil', 'Lime wedges'],
 steps: ['Sauté curry paste for 1 minute', 'Pour in coconut milk and bring to a simmer', 'Add chicken or tofu and cook through', 'Stir in vegetables and simmer for 8 minutes', 'Finish with Thai basil and lime'],
 },
 {
 id: 'r6',
 emoji: '',
 name: 'Fluffy Banana Pancakes',
 category: 'Breakfast',
 diet: ['Vegetarian'],
 prepTime: '5min',
 cookTime: '15min',
 totalMinutes: 20,
 servings: '2 servings',
 difficulty: 'Easy',
 calories: '340cal',
 rating: 4.7,
 ratingCount: 980,
 description: 'Soft, sweet pancakes that turn ripe bananas into a weekend treat.',
 ingredients: ['1 ripe banana', '1 egg', '1 cup self-raising flour', '3/4 cup milk', '1 tsp vanilla', 'Butter for the pan', 'Maple syrup'],
 steps: ['Mash banana until smooth', 'Whisk in egg, milk and vanilla', 'Fold through flour until just combined', 'Cook scoops of batter for 2 minutes per side', 'Serve warm with maple syrup'],
 },
 {
 id: 'r7',
 emoji: '',
 name: 'Teriyaki Salmon Bowl',
 category: 'Lunch',
 diet: ['Gluten-Free'],
 prepTime: '10min',
 cookTime: '20min',
 totalMinutes: 30,
 servings: '2 servings',
 difficulty: 'Easy',
 calories: '520cal',
 rating: 4.9,
 ratingCount: 780,
 description: 'Sticky glazed salmon over rice with crunchy cucumber, edamame and sesame.',
 ingredients: ['2 salmon fillets', '2 cups cooked rice', '2 tbsp tamari', '1 tbsp honey', '1 tsp grated ginger', '1 cup edamame', '1 cucumber', 'Sesame seeds'],
 steps: ['Whisk tamari, honey and ginger', 'Brush salmon with glaze', 'Bake or pan-sear salmon for 10 minutes', 'Assemble bowls with rice, cucumber and edamame', 'Top with salmon and sesame seeds'],
 },
 {
 id: 'r8',
 emoji: '',
 name: 'Guacamole & Chips',
 category: 'Snacks',
 diet: ['Vegan', 'Gluten-Free'],
 prepTime: '10min',
 cookTime: '0min',
 totalMinutes: 10,
 servings: '4 servings',
 difficulty: 'Easy',
 calories: '220cal',
 rating: 4.8,
 ratingCount: 1670,
 description: 'Chunky guac with lime, coriander and the perfect salty crunch on the side.',
 ingredients: ['3 ripe avocados', '1 lime', '1/4 red onion', '1 tomato', 'Fresh coriander', 'Salt', 'Corn chips'],
 steps: ['Mash avocado lightly with lime juice', 'Fold through onion, tomato and coriander', 'Season generously with salt', 'Let flavours mingle for 5 minutes', 'Serve with corn chips'],
 },
 {
 id: 'r9',
 emoji: '',
 name: 'Lemon Tart',
 category: 'Desserts',
 diet: ['Vegetarian'],
 prepTime: '30min',
 cookTime: '40min',
 totalMinutes: 70,
 servings: '8 servings',
 difficulty: 'Hard',
 calories: '310cal',
 rating: 4.8,
 ratingCount: 560,
 description: 'Silky lemon filling in a crisp butter pastry shell with a glossy finish.',
 ingredients: ['1 tart shell', '4 lemons', '4 eggs', '3/4 cup caster sugar', '150ml cream', '80g butter', 'Extra zest'],
 steps: ['Blind bake the tart shell until golden', 'Whisk lemon juice, zest, eggs and sugar', 'Cook gently with cream until thickened', 'Whisk in butter until glossy', 'Pour into shell and bake for 15 minutes to set'],
 },
 {
 id: 'r10',
 emoji: '',
 name: 'Green Immunity Smoothie',
 category: 'Drinks',
 diet: ['Vegan', 'Gluten-Free'],
 prepTime: '5min',
 cookTime: '0min',
 totalMinutes: 5,
 servings: '1 serving',
 difficulty: 'Easy',
 calories: '180cal',
 rating: 4.6,
 ratingCount: 890,
 description: 'Refreshing, zingy and packed with greens, citrus and ginger.',
 ingredients: ['1 banana', '1 cup spinach', '1 kiwi', '1/2 cucumber', '1 orange', '1 tsp grated ginger', '1 cup coconut water'],
 steps: ['Add all ingredients to a blender', 'Blend until completely smooth', 'Taste and add extra citrus if needed', 'Pour into a chilled glass'],
 },
 {
 id: 'r11',
 emoji: '',
 name: 'Sourdough Pizza Margherita',
 category: 'Dinner',
 diet: ['Vegetarian'],
 prepTime: '20min',
 cookTime: '12min',
 totalMinutes: 32,
 servings: '2 servings',
 difficulty: 'Medium',
 calories: '560cal',
 rating: 4.9,
 ratingCount: 2300,
 description: 'Crisp, blistered sourdough crust with tomato, mozzarella and basil.',
 ingredients: ['2 sourdough pizza bases', '1/2 cup tomato sauce', '200g fresh mozzarella', 'Fresh basil', 'Olive oil', 'Sea salt'],
 steps: ['Preheat pizza stone or tray', 'Spread sauce over the dough', 'Add torn mozzarella evenly', 'Bake for 10 to 12 minutes until blistered', 'Finish with basil, olive oil and sea salt'],
 },
 {
 id: 'r12',
 emoji: '',
 name: 'Falafel Wrap',
 category: 'Lunch',
 diet: ['Vegan'],
 prepTime: '20min',
 cookTime: '20min',
 totalMinutes: 40,
 servings: '4 servings',
 difficulty: 'Medium',
 calories: '420cal',
 rating: 4.7,
 ratingCount: 670,
 description: 'Crispy falafel wrapped with crunchy salad, pickles and tahini sauce.',
 ingredients: ['12 falafel', '4 flatbreads', '2 tomatoes', '1 cucumber', 'Pickles', 'Lettuce', 'Tahini sauce'],
 steps: ['Cook falafel until crisp', 'Warm the flatbreads', 'Slice salad vegetables and pickles', 'Spread tahini over each wrap', 'Fill, roll and serve immediately'],
 },
 {
 id: 'r13',
 emoji: '',
 name: 'Matcha Chia Pudding',
 category: 'Breakfast',
 diet: ['Vegan', 'Gluten-Free'],
 prepTime: '5min',
 cookTime: '0min + 4hr set',
 totalMinutes: 245,
 servings: '2 servings',
 difficulty: 'Easy',
 calories: '240cal',
 rating: 4.6,
 ratingCount: 450,
 description: 'Creamy make-ahead pudding with matcha, vanilla and fresh berries.',
 ingredients: ['1 1/2 cups almond milk', '1/4 cup chia seeds', '1 tsp matcha', '1 tbsp maple syrup', '1/2 tsp vanilla', 'Fresh berries'],
 steps: ['Whisk almond milk, matcha, maple and vanilla', 'Stir in chia seeds thoroughly', 'Re-stir after 5 minutes to prevent clumps', 'Chill for at least 4 hours', 'Top with berries before serving'],
 },
 {
 id: 'r14',
 emoji: '',
 name: 'Butter Chicken',
 category: 'Dinner',
 diet: ['Gluten-Free'],
 prepTime: '15min',
 cookTime: '35min',
 totalMinutes: 50,
 servings: '4 servings',
 difficulty: 'Medium',
 calories: '490cal',
 rating: 4.9,
 ratingCount: 3200,
 description: 'Rich tomato curry with tender chicken, warming spices and a velvety finish.',
 ingredients: ['600g chicken thigh', '1 onion', '3 cloves garlic', '1 tbsp ginger', '2 tbsp butter', '400g tomato puree', '1/2 cup cream', 'Garam masala'],
 steps: ['Brown chicken pieces in butter', 'Sauté onion, garlic and ginger until soft', 'Add tomato puree and spices, then simmer for 20 minutes', 'Return chicken and cook until tender', 'Stir in cream and serve with rice'],
 },
 {
 id: 'r15',
 emoji: '',
 name: 'No-Bake Energy Balls',
 category: 'Snacks',
 diet: ['Vegan', 'Gluten-Free'],
 prepTime: '15min',
 cookTime: '0min',
 totalMinutes: 15,
 servings: '12 balls',
 difficulty: 'Easy',
 calories: '120cal',
 rating: 4.7,
 ratingCount: 890,
 description: 'Chocolatey, chewy snack bites made for meal prep and afternoon cravings.',
 ingredients: ['1 cup oats', '1/2 cup dates', '1/4 cup peanut butter', '2 tbsp cocoa powder', '2 tbsp chia seeds', 'Pinch of salt'],
 steps: ['Blitz oats and dates in a processor', 'Add peanut butter, cocoa and chia', 'Pulse until the mixture clumps together', 'Roll into bite-sized balls', 'Chill for 15 minutes before eating'],
 },
 {
 id: 'r16',
 emoji: '',
 name: 'Vanilla Cupcakes',
 category: 'Desserts',
 diet: ['Vegetarian'],
 prepTime: '20min',
 cookTime: '20min',
 totalMinutes: 40,
 servings: '12 cupcakes',
 difficulty: 'Easy',
 calories: '280cal',
 rating: 4.7,
 ratingCount: 1200,
 description: 'Soft vanilla cupcakes topped with a buttery frosting swirl.',
 ingredients: ['1 1/2 cups flour', '1 cup sugar', '2 eggs', '1/2 cup butter', '1/2 cup milk', '1 tsp vanilla', 'Buttercream frosting'],
 steps: ['Cream butter and sugar until pale', 'Beat in eggs one at a time', 'Fold in flour, milk and vanilla', 'Bake for 20 minutes until springy', 'Cool completely before frosting'],
 },
 {
 id: 'r17',
 emoji: '',
 name: 'Dalgona Whipped Coffee',
 category: 'Drinks',
 diet: ['Vegan'],
 prepTime: '5min',
 cookTime: '0min',
 totalMinutes: 5,
 servings: '1 serving',
 difficulty: 'Easy',
 calories: '90cal',
 rating: 4.8,
 ratingCount: 2100,
 description: 'Velvety whipped coffee floating over icy milk for a café-style treat.',
 ingredients: ['2 tbsp instant coffee', '2 tbsp sugar', '2 tbsp hot water', '1 cup oat milk', 'Ice cubes', 'Cocoa dusting'],
 steps: ['Whisk coffee, sugar and hot water for 3 minutes until fluffy', 'Fill a glass with ice and milk', 'Spoon whipped coffee over the top', 'Finish with cocoa if desired'],
 },
 {
 id: 'r18',
 emoji: '',
 name: 'Perfect Shakshuka',
 category: 'Lunch',
 secondaryCategory: 'Breakfast',
 diet: ['Vegetarian'],
 prepTime: '10min',
 cookTime: '25min',
 totalMinutes: 35,
 servings: '4 servings',
 difficulty: 'Easy',
 calories: '290cal',
 rating: 4.8,
 ratingCount: 1560,
 description: 'Eggs gently poached in a smoky tomato and capsicum sauce with warm spices.',
 ingredients: ['1 onion', '1 red capsicum', '3 cloves garlic', '1 tsp cumin', '1 tsp smoked paprika', '400g crushed tomatoes', '4 eggs', 'Parsley'],
 steps: ['Cook onion and capsicum until softened', 'Add garlic and spices for 1 minute', 'Pour in tomatoes and simmer for 15 minutes', 'Make wells and crack eggs into the sauce', 'Cover and cook for 6 minutes, then finish with parsley'],
 },
 {
 id: 'r19',
 emoji: '',
 name: 'Crispy Salt & Pepper Tofu',
 category: 'Snacks',
 diet: ['Vegan', 'Gluten-Free'],
 prepTime: '10min',
 cookTime: '15min',
 totalMinutes: 25,
 servings: '4 servings',
 difficulty: 'Easy',
 calories: '180cal',
 rating: 4.7,
 ratingCount: 340,
 description: 'Ultra-crisp tofu tossed with chilli, garlic, spring onion and a punchy pepper salt.',
 ingredients: ['400g firm tofu', '2 tbsp cornflour', '1 tsp sea salt', '1 tsp cracked pepper', '1 red chilli', '2 spring onions', '1 clove garlic'],
 steps: ['Press and cube the tofu', 'Coat with cornflour, salt and pepper', 'Pan-fry until crisp for 10 minutes', 'Toss with chilli, spring onion and garlic for 1 minute', 'Serve immediately while crunchy'],
 },
 {
 id: 'r20',
 emoji: '',
 name: 'Prawn Pad Thai',
 category: 'Dinner',
 diet: ['Gluten-Free'],
 prepTime: '15min',
 cookTime: '15min',
 totalMinutes: 30,
 servings: '2 servings',
 difficulty: 'Medium',
 calories: '510cal',
 rating: 4.9,
 ratingCount: 1890,
 description: 'Sweet, tangy and savoury rice noodles with juicy prawns and crunchy peanuts.',
 ingredients: ['200g rice noodles', '200g prawns', '2 eggs', '2 tbsp tamarind paste', '1 tbsp fish sauce', '1 tbsp brown sugar', 'Bean sprouts', 'Crushed peanuts'],
 steps: ['Soak rice noodles until pliable', 'Whisk tamarind, fish sauce and sugar', 'Sear prawns for 2 minutes per side', 'Scramble eggs, then toss in noodles and sauce', 'Finish with bean sprouts, peanuts and lime'],
 },
];

const RecipeContext = createContext(null);

const initialState = {
 phase: 'home',
 selectedRecipe: null,
 cookStep: 0,
 filters: { category: 'All', diet: 'All', time: 'Any' },
 saved: ['r2', 'r7'],
 chatOpen: false,
 chatMessages: [],
 chatInput: '',
};

function recipeReducer(state, action) {
 switch (action.type) {
 case 'SET_PHASE':
 return { ...state, phase: action.payload };
 case 'SELECT_RECIPE':
 return { ...state, selectedRecipe: action.payload, phase: 'recipe', cookStep: 0 };
 case 'START_COOKING':
 return { ...state, phase: 'cook', cookStep: 0 };
 case 'SET_COOK_STEP':
 return { ...state, cookStep: action.payload };
 case 'NEXT_COOK_STEP':
 return { ...state, cookStep: Math.min(state.cookStep + 1, (state.selectedRecipe?.steps?.length || 1) - 1) };
 case 'PREV_COOK_STEP':
 return { ...state, cookStep: Math.max(state.cookStep - 1, 0) };
 case 'TOGGLE_SAVE': {
 const exists = state.saved.includes(action.payload);
 return {
 ...state,
 saved: exists ? state.saved.filter((id) => id !== action.payload) : [...state.saved, action.payload],
 };
 }
 case 'SET_FILTER':
 return { ...state, filters: { ...state.filters, [action.key]: action.value } };
 case 'TOGGLE_CHAT':
 return { ...state, chatOpen: action.payload ?? !state.chatOpen };
 case 'SET_CHAT_INPUT':
 return { ...state, chatInput: action.payload };
 case 'SEND_CHAT_MESSAGE':
 return {
 ...state,
 chatInput: '',
 chatOpen: true,
 chatMessages: [
 ...state.chatMessages,
 { id: `${Date.now()}-user`, role: 'user', text: action.payload.userText },
 { id: `${Date.now()}-assistant`, role: 'assistant', text: action.payload.assistantText },
 ],
 };
 default:
 return state;
 }
}

export function RecipeProvider({ children }) {
 const [state, dispatch] = useReducer(recipeReducer, initialState);

 const value = useMemo(
 () => ({
 state,
 dispatch,
 recipes,
 categories,
 diets,
 timeOptions,
 }),
 [state]
 );

 return <RecipeContext.Provider value={value}>{children}</RecipeContext.Provider>;
}

export function useRecipeStore() {
 const context = useContext(RecipeContext);
 if (!context) {
 throw new Error('useRecipeStore must be used within a RecipeProvider');
 }
 return context;
}
